os: Visual Studio 2017
environment:
    matrix:
      - arch: x64
        compiler: msvc2017
install:
  # Install lz4
  - ps: Invoke-WebRequest "https://github.com/facebook/zstd/releases/download/v1.4.2/zstd-v1.4.2-win64.zip" -OutFile "C:\zstd.zip"
  - ps: Expand-Archive "C:\zstd.zip" -DestinationPath "C:\Libraries"
  # Install cereal
  - ps: Invoke-WebRequest "https://github.com/USCiLab/cereal/archive/v1.2.2.zip" -OutFile "C:\cereal.zip"
  - ps: Expand-Archive "C:\cereal.zip" -DestinationPath "C:\Libraries"
  # Debug
  - cd C:\Libraries\zstd-v1.4.2-win64
  - tree /f
  - cd %APPVEYOR_BUILD_FOLDER%
  # Download ninja
  - cmd: cinst ninja
  # Set paths to dependencies
  - cmd: set PYTHON_ROOT=C:\python37-x64
  # Set-up qt5
  - cmd: set QT_ROOT=C:\Qt\5.13.0\%compiler%_64
  # Add neccessary paths to PATH variable
  - cmd: set PATH=%cd%;C:\ninja-build;%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%QT_ROOT%\bin;%PATH%
  # Install meson
  - cmd: pip install meson
  # Setup Boost
  - cmd: set BOOST_ROOT=C:\Libraries\boost_1_69_0
  # Set up the build environment
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch%
  # - cd c:\tools\vcpkg
  # - vcpkg integrate install

build_script:
  - cmd: echo Building on %arch% with %compiler%
  - cmd: meson -Dweb=false -Dzstd_dir="C:\Libraries\zstd-v1.4.2-win64" -Dopenssl_dir="C:\OpenSSL-v111-Win64" -Dcereal_dir="C:\Libraries\cereal-1.2.2" -Dboost_dir="C:\Libraries\boost_1_69_0" --backend=ninja builddir
  - cmd: ninja -C builddir -k5
