os: Visual Studio 2017
environment:
    matrix:
      - arch: x64
        compiler: msvc2017
install:
  # Download ninja
  - cinst ninja
  # Set paths to dependencies
  - cmd: set PYTHON_ROOT=C:\python37-x64
  # Add neccessary paths to PATH variable
  - cmd: set PATH=%cd%;C:\ninja-build;%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PATH%
  # Install meson
  - cmd: pip install meson lz4
  # Setup Boost
  - cmd: set BOOST_ROOT=C:\Libraries\boost_1_67_0
  # Set up the build environment
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch%
build_script:
  - cmd: echo Building on %arch% with %compiler%
  - cmd: meson --backend=ninja builddir
  - cmd: ninja -C builddir
