environment:
    matrix:
      - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1804
        arch: x64
        compiler: clang
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        arch: x64
        compiler: msvc2017
install:
  # Ubuntu: Install dependencies
  - sh: sudo add-apt-repository ppa:mhier/libboost-latest
  - sh: sudo apt-get update
  - sh: sudo apt-get install -y -f ninja-build meson libzstd-dev libcereal-dev libboost1.70-dev qtbase5-dev qt5-default
  # Windows: Install lz4
  - ps: if ($isWindows) { Invoke-WebRequest "https://github.com/facebook/zstd/releases/download/v1.4.2/zstd-v1.4.2-win64.zip" -OutFile "C:\zstd.zip" }
  - ps: if ($isWindows) { Expand-Archive "C:\zstd.zip" -DestinationPath "C:\Libraries" }
  # Windows: Install cereal
  - ps: if ($isWindows) { Invoke-WebRequest "https://github.com/USCiLab/cereal/archive/v1.2.2.zip" -OutFile "C:\cereal.zip" }
  - ps: if ($isWindows) { Expand-Archive "C:\cereal.zip" -DestinationPath "C:\Libraries" }
    # Windows: Install Ninja
  - cmd: cinst ninja
    # Windows: Set paths to dependencies
  - cmd: set PYTHON_ROOT=C:\python37-x64
  - cmd: set QT_ROOT=C:\Qt\5.13.0\%compiler%_64
  - cmd: set PATH=%cd%;C:\ninja-build;%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%QT_ROOT%\bin;%PATH%
  # Windows: Install meson
  - cmd: pip install meson
  # Windows: Setup Boost
  - cmd: set BOOST_ROOT=C:\Libraries\boost_1_69_0
  # Windows: Set up the build environment
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch%

build_script:
  # Windows
  - cmd: meson -Dweb=false -Dzstd_dir="C:\Libraries\zstd-v1.4.2-win64" -Dopenssl_dir="C:\OpenSSL-v111-Win64" -Dcereal_dir="C:\Libraries\cereal-1.2.2" -Dboost_dir="C:\Libraries\boost_1_69_0" --backend=ninja build
  - cmd: ninja -C build -k5
  # Ubuntu
  - sh: meson build -Dweb=false
  - sh: ninja -C build -k5
