---
kind: pipeline
type: docker
name: ubuntu-ui

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: build
  image: svendcsvendsen/judoassistant-ubuntu
  commands:
  - meson --buildtype=release build-release
  - ninja -j2 -C build-release
---
kind: pipeline
type: docker
name: ubuntu-web

steps:
- name: build
  image: svendcsvendsen/judoassistant-ubuntu
  commands:
  - meson --buildtype=release -Dui=false -Dweb=true build-release
  - ninja -j2 -C build-release
