sudo: false
os:
  - linux
dist: bionic
compiler: clang
addons:
    apt:
        sources:
          - sourceline: 'ppa:mhier/libboost-latest'
        packages:
          - ninja-build
          - meson
          - liblz4-dev
          - libbotan-2-dev
          - libcereal-dev
          - rapidjson-dev
          - libpqxx-dev
          - libboost1.70-dev
language:
  - cpp
notifications:
  email: false
script:
  - $CC --version
  - $CXX --version
  - meson -Dui=false build && cd build && ninja -k 0

