sudo: false
os:
  - linux
dist: bionic
compiler: clang
addons:
    apt:
        sources:
          - sourceline: 'ppa:mhier/libboost-latest'
        packages:
          - ninja-build
          - meson
          - liblz4-dev
          - libbotan-2-dev
          - libcereal-dev
          - rapidjson-dev
          - libpqxx-dev
          - libboost1.70-dev
          - qtbase5-dev
          - qt5-default
language:
  - cpp
notifications:
  email: false
script:
  - meson build && cd build && ninja -k 0

