#pragma once

#include "core/serialize.hpp"

#include "core/actions/actions.hpp"
#include "core/draw_systems/draw_systems.hpp"
#include "core/rulesets/rulesets.hpp"
#include "core/stores/category_store.hpp"
#include "core/stores/match_store.hpp"
#include "core/stores/player_age.hpp"
#include "core/stores/player_country.hpp"
#include "core/stores/player_rank.hpp"
#include "core/stores/player_sex.hpp"
#include "core/stores/player_sex.hpp"
#include "core/stores/player_store.hpp"
#include "core/stores/player_weight.hpp"
#include "core/stores/preferences_store.hpp"
#include "core/stores/tatami/location.hpp"
#include "core/stores/tatami/tatami_list.hpp"
#include "core/stores/tournament_store.hpp"
#include "core/version.hpp"
